### ISSUE TITLE
Error of too many files

### ISSUE THREAD

**Issue by xs005** [tchiotludo/kafkahq#105]
Occasionally, I got this error. I am using docker to run KafkaHQ 0.9.0. It may use JVM with many other containers. Is that the reason of the too many files error?

`2019-08-17 20:40:18,563 ERROR l-worker-3 i.m.c.DefaultBeanContext   Parallel Bean definition [io.micronaut.scheduling.io.watch.DefaultWatchThread] could not be loaded: Error instantiating bean of type  [io.micronaut.scheduling.io.watch.DefaultWatchThread]

Message: User limit of inotify instances reached or too many open files

Path Taken: new DefaultWatchThread(ApplicationEventPublisher eventPublisher,FileWatchConfiguration configuration,[WatchService watchService])

io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.scheduling.io.watch.DefaultWatchThread]

Message: User limit of inotify instances reached or too many open files

Path Taken: new DefaultWatchThread(ApplicationEventPublisher eventPublisher,FileWatchConfiguration configuration,[WatchService watchService])

at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1512)

at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:1956)

at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1858)

at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1836)

at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:997)

at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:982)

at io.micronaut.scheduling.io.watch.$DefaultWatchThreadDefinition.build(Unknown Source)

at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1494)

at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2170)

at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:1778)

at io.micronaut.context.DefaultBeanContext.lambda$null$44(DefaultBeanContext.java:1622)

at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)

at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)

at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)

at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)

at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)

at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

Caused by: java.io.IOException: User limit of inotify instances reached or too many open files

at java.base/sun.nio.fs.LinuxWatchService.<init>(LinuxWatchService.java:64)

at java.base/sun.nio.fs.LinuxFileSystem.newWatchService(LinuxFileSystem.java:47)

at io.micronaut.scheduling.io.watch.WatchServiceFactory.watchService(WatchServiceFactory.java:58)

at io.micronaut.scheduling.io.watch.$WatchServiceFactory$WatchServiceDefinition.build(Unknown Source)

at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1494)

... 16 common frames omitted

2019-08-17 20:40:18,781 INFO  main       i.m.runtime.Micronaut      Startup completed in 5296ms. Server Running: http://kafkahq:8080

2019-08-17 20:40:21,964 INFO  Thread-2   i.m.runtime.Micronaut      Embedded Application shutting down`

**Comment by tchiotludo** [comment]
Are you using the official docker image from : https://hub.docker.com/r/tchiotludo/kafkahq ? 

to be honest, the error is coming from micronaut, but I 'm really surprised that filewatch is enabled on docker image

**Comment by tchiotludo** [comment]
I think it because of this : https://github.com/tchiotludo/kafkahq/blob/dev/src/main/resources/application.yml#L4

FileWatcher is enabled regardless of env, this one is only necessary for dev, I must look at how to remove this and enabled it only on dev env
