### ISSUE TITLE
Handle broken schemas

### ISSUE THREAD

**Issue by chromy96** [tchiotludo/kafkahq#130]
Hi,

I was testing kafkahq on our test environment and I ran into the situation where a badly written Avro schema broke down KafkaHQ.

One of the nullable fields wasn't defined correctly, and kafkahq displayed this exception when accessing /schema page.
```
Caused by: org.apache.avro.AvroTypeException: Non-string default value for string: null
	at org.apache.avro.Schema.validateDefault(Schema.java:1512)
	at org.apache.avro.Schema.access$300(Schema.java:86)
	at org.apache.avro.Schema$Field.<init>(Schema.java:493)
	at org.apache.avro.Schema.parse(Schema.java:1619)
	at org.apache.avro.Schema$Parser.parse(Schema.java:1366)
	at org.apache.avro.Schema$Parser.parse(Schema.java:1354)
	at org.kafkahq.models.Schema.<init>(Schema.java:26)
	at org.kafkahq.repositories.SchemaRegistryRepository.getLatestVersion(SchemaRegistryRepository.java:85)
	at org.kafkahq.repositories.SchemaRegistryRepository.lambda$getAll$1(SchemaRegistryRepository.java:39)
```
One option could be to filter out the schemas that are causing these errors. 
Even better approach would be to display the schema and somehow visually show it contains errors.

Let me know what you think.  I could help out on this issue.

**Comment by tchiotludo** [comment]
just fix it yesterday, on dev branch : https://github.com/tchiotludo/kafkahq/commit/eaf83bff17dad084e1ac4fc4b9b8f6101193bed9

relate #89

**Comment by tchiotludo** [comment]
release 0.11.0 include this improvement, no need to compile it anymore :)
