### ISSUE TITLE
Couldn't find any clusters on your configuration file

### ISSUE THREAD

**Issue by Frietziek** [tchiotludo/kafkahq#63]
Hello, i am having trouble when starting kafkahq:

``` java
java.lang.IllegalArgumentException: Couldn't find any clusters on your configuration file, please ensure that the configuration file is loaded correctly
	at org.kafkahq.middlewares.KafkaWrapperFilter.doFilter(KafkaWrapperFilter.java:30)
	at io.micronaut.http.filter.HttpServerFilter.doFilter(HttpServerFilter.java:48)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.filterPublisher(RoutingInBoundHandler.java:1449)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.exceptionCaughtInternal(RoutingInBoundHandler.java:302)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.exceptionCaught(RoutingInBoundHandler.java:222)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
	at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:850)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:364)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:191)
	at io.micronaut.http.netty.stream.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:121)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:187)
	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at org.kafkahq.middlewares.HttpServerAccessLogHandler.channelRead(HttpServerAccessLogHandler.java:95)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

I start it with:

```bash
sudo docker run \
 -p 8080:8080 \
 -v /home/my-user/projects/kafkahq/my-config.yml \
 tchiotludo/kafkahq

```

And put the proper kafka cluster configuration, using the template provided in this repo and changing only this part:

```yml
connections:
    my-cluster-plain-text: "my-kafka-test" #url friendly name for the cluster
      properties: # standard kafka properties (optional)
        bootstrap.servers: "mykafkahost1:9092,mykafkahost2:9092,mykafkahost3:9092"
```

Any help is appreciated!

**Comment by tchiotludo** [comment]
Hello, 

Your configuration files is invalid and must be like that :  
```yaml
kafkahq: 
  connections:
    my-kafka-test:
      properties:
        bootstrap.servers: "mykafkahost1:9092,mykafkahost2:9092,mykafkahost3:9092"
```
After must be working as I see

**Comment by Frietziek** [comment]
Mmm, i am doing that now (put my-kafka-test in that way), but i still have the same error. I also tried using the example config of this repo without modification and still the same problem...It can be an connection problem with my kafka? The error looks like something is bad when parsing configuration file or something like that, not like a conection problem with my instances.

**Comment by tchiotludo** [comment]
The error clairly state that the file is not found or the format invalid.

On the fragment I didn't see the `kafkahq: ` hope it was here, if not I can't work. 

Just see also your docker run seems invalid, here is the good one as I understand : 

```bash 
docker run -d \
    -p 8080:8080 \
    -v /home/my-user/projects/kafkahq/my-config.yml:/app/application.yml \
    tchiotludo/kafkahq
```

Hope it help

**Comment by Frietziek** [comment]
It works now! Thanks!

**Comment by federicovagnoni** [comment]
I'm having the same problem, but I really cannot understand what I'm doing wrong!

```
kafkahq:
  # list of kafka cluster available for kafkahq
  connections:
    test-1: # url friendly name for the cluster (letter, number, _, -, ... dot are not allowed here)
      properties: # standard kafka properties (optional)
        bootstrap.servers: "localhost:9092"

  # Basic auth configuration
  basic-auth:
    user: # Username
      password: pass # Password in sha256
      roles: # Role for current users
        - topic/read
        - group/read
        - group/delete
```

I launch the container in this way, because kafka is running locally.

```
docker run -d \
    --network="host" \
    -e MICRONAUT_CONFIG_FILES=/app/micronaut.properties \
    -v /data/kafkahq/micronaut/application.properties:/app/micronaut.properties \
    -v /data/kafkahq/application.yml:/app/application.yml \
    tchiotludo/kafkahq
```

**Comment by souljungkim** [comment]
@federicovagnoni Check the permission of the shared file.

In my case

```bash
docker run -d --name kafka-hq --net host -v $PWD/akhq/application.yml:/app/application.yml tchiotludo/kafkahq
```

When I connect akhq from the browser.

## 1. Error - `Permission Denied`

1. Checking `application.yml`'s permission.
    ```bash
    docker exec -it kafka-hq ls -al /app
    ```
    then I found the permission is `?????????`

2. Trying to cat application.yml on volume
    ```bash
    docker exec -it kafka-hq ls cat /app/application.yml
    ```
    then I found error `Permission Denied` 

## 2. Solved

- add `:Z` to your last of volume options
    ```bash
    docker run -d --name kafka-hq --net host -v $PWD/akhq/application.yml:/app/application.yml:Z tchiotludo/kafkahq
    ```

OR

- Not Good Way
    ```bash
    docker run -d --name kafka-hq --net host --priviliged=true -v $PWD/akhq/application.yml:/app/application.yml tchiotludo/kafkahq
    ```

**Comment by tchiotludo** [comment]
@souljungkim, You should also move from image here `tchiotludo/kafkahq` that will be drop ! 
the new one is `tchiotludo/akhq `

**Comment by Railac** [comment]
hi, I'm having the same problem. It starts but doesn't connect to the UI.

`akhq:
  connections:
    my-kafka-test:
      properties:
        bootstrap.servers: "172.16.60.211:9092,172.16.60.212:9092,172.16.60.213:9092"
      schema-registry:
        url: "http://schema-registry:8085"
      connect:
        - name: "connect"
          url: "http://connect:8083"
      ksqldb:
        - name: "ksqldb"
          url: "http://ksqldb:8088"`
