### ISSUE TITLE
Schema parser exception crashes schema registry view

### ISSUE THREAD

**Issue by teebee** [tchiotludo/kafkahq#89]
If some schema cannot be parsed successfully, the schema registry view shows only the corresponding exception and is no longer usable:

```
org.apache.avro.AvroTypeException: Invalid default for field [...]
[...]
Caused by: org.apache.avro.AvroTypeException: Invalid default for field [...]
        at org.apache.avro.Schema.validateDefault(Schema.java:1512)
        at org.apache.avro.Schema.access$300(Schema.java:86)
        at org.apache.avro.Schema$Field.<init>(Schema.java:493)
        at org.apache.avro.Schema.parse(Schema.java:1619)
        at org.apache.avro.Schema.parse(Schema.java:1648)
        at org.apache.avro.Schema.parse(Schema.java:1609)
        at org.apache.avro.Schema.parse(Schema.java:1692)
        at org.apache.avro.Schema.parse(Schema.java:1609)
        at org.apache.avro.Schema$Parser.parse(Schema.java:1366)
        at org.apache.avro.Schema$Parser.parse(Schema.java:1354)
        at org.kafkahq.models.Schema.<init>(Schema.java:26)
        at org.kafkahq.repositories.SchemaRegistryRepository.getLatestVersion(SchemaRegistryRepository.java:85)
        at org.kafkahq.repositories.SchemaRegistryRepository.lambda$getAll$1(SchemaRegistryRepository.java:39)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by tchiotludo** [comment]
How can you have this error ? 
The Schema Registry don't accept invalid schema as I know and validate schema before allow to register the schema registry

**Comment by anto59** [comment]
Same error on schema registry view: org.apache.avro.AvroTypeException: Invalid default for field null not a {...}
This error occurs only on the 0.9.0 version. (No issue on 0.7.2)

**Comment by tchiotludo** [comment]
Ok, I've updated to avro 1.9.
Maybe this version is more resilient to error.
Will catch this error on future release

**Comment by tchiotludo** [comment]
Official release is also here !

**Comment by anto59** [comment]
This problem still occurs on 0.10 version.
_org.apache.avro.AvroTypeException: Invalid default for field_

**Comment by tchiotludo** [comment]
really weird, the commit has disappeared ... 
most have failed a merge. 
Will be ok on few minutes on dev branch
